### ISSUE TITLE
Unimplemented  in `plonk/polynomials/polynomial_arithmetic.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#12]
# Polynomial Arithmetic

- [x] Implement `EvaluationDomain::coset_fft_inplace()` 
- [x] Implement `EvaluationDomain::coset_fft_vec_inplace()`
- [x] Implement `EvaluationDomain::coset_fft()`
- [x] Implement `EvaluationDomain::coset_fft_with_generator_shift()`

**Comment by lonerapier** [comment]
@Autoparallel you working on this? Mind if I try it?

**Comment by Autoparallel** [comment]
I'm happy for you to take it, but I'd also like to give it a shot :)

**Comment by Autoparallel** [comment]
What if we team worked it?

**Comment by lonerapier** [comment]
No worries sir. I'll try something else :D

**Comment by Autoparallel** [comment]
I'd be happy to work together. This repo is pretty new to me and it's a lot to learn.

**Comment by lonerapier** [comment]
Same, new to the repo as well. There are more unimplemented functions, also tests needs to be added as well. We can distribute, so you can implement these, I can take up those. Does that sound good?

**Comment by Autoparallel** [comment]
@lonerapier sounds good to me.

**Comment by laudiacay** [comment]
@shuklaayush did you finish this?

**Comment by shuklaayush** [comment]
Yeah, I think so

**Comment by Autoparallel** [comment]
@shuklaayush do you have a PR?

**Comment by shuklaayush** [comment]
No PR. Actually, I think I ended up implementing all the functions that were being used in other parts of the code. So `coset_inplace`functions are done. I didn't bother with the other ones (non-inplace versions) since I don't think they're used anywhere

https://github.com/laudiacay/barustenberg/blob/6deff3351031a0ed26d30cbca6e108a5e80949b5/barustenberg/src/polynomials/polynomial_arithmetic.rs#L727-L763

**Comment by Autoparallel** [comment]
@shuklaayush I see. I have updated the description of this issue now.

@lonerapier I fell off getting this done. There are two more functions to implement. Want to take them? :)

**Comment by lonerapier** [comment]
Sure @Autoparallel.
