### ISSUE TITLE
implement following functions in polynomial arithmetic

### ISSUE THREAD

**Issue by lonerapier** [laudiacay/barustenberg#14]
```rust
pub(crate) fn divide_by_pseudo_vanishing_polynomial(&self, _coeffs: &[&mut [&mut Fr]], _target: &EvaluationDomain<'a, Fr>, _num_roots_cut_out_of_vanishing_poly: usize);

pub(crate) fn compute_kate_opening_coefficients<Fr: Field>(src: Fr, dest: Fr, z: usize, n: usize) -> Fr;

pub(crate) fn get_lagrange_evaluation<Fr: Field>(zeta: &Fr, _domain: &EvaluationDomain<'a, Fr>, _num_roots_cut_out_of_vanishing_polynomial: usize);

pub(crate) fn compute_barycentric_evaluation<Fr: Field>(_coeffs: &[Fr], _num_coeffs: usize, z: &Fr, domain: &EvaluationDomain<'a, Fr>) -> Fr;
```

**Comment by lonerapier** [comment]
@laudiacay / @0xJepsen can either of you confirm whether these are needed.

**Comment by laudiacay** [comment]
If you can
1. Find a call to them in other code (I think all 4 do have those calls)
2. They have a todo or unimplemented inside

Yes :D thank you!!

Sorry, on mobile- I will review when you're done. 

Current standard is "compiles, and you honestly think the code is correct"- do not check in dubious code without a big TODO comment or macro in it to flag it as a potential problem for when we hit QA stage.

If you find relevant tests in the OG repo and can add them, that is a highly appreciated bonus.
