### ISSUE TITLE
Implement `divide_by_pseudo_vanishing_polynomial`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#17]
# Problem

The function is in `polynomials/polynomial_arithmetic.rs` and takes the form:
```rust
    pub(crate) fn divide_by_pseudo_vanishing_polynomial(
        &self,
        _coeffs: &[&mut [&mut Fr]],
        _target: &EvaluationDomain<'a, Fr>,
        _num_roots_cut_out_of_vanishing_poly: usize,
    ) {
        unimplemented!()
    }
```

I am not sure exactly what this function should be doing mathematically.

**Comment by lonerapier** [comment]
@Autoparallel, I was planning to do this #14. Just asking if you have you completed it, if yes, then I would drop it?
Also, can we do something to distribute and coordinate better?

**Comment by laudiacay** [comment]
looks done
