### ISSUE TITLE
make issues for all of the various todos and unimplementeds hiding in the repo :)

### ISSUE THREAD

**Issue by laudiacay** [laudiacay/barustenberg#27]

**Comment by lonerapier** [comment]
me and @PatStiles have started working on pippenger MSM. will create an issue.

**Comment by laudiacay** [comment]
Sambhav/pat are you guys looking at the miler algo at all? I am right now-
don’t want to overlap- it’s in the issue about filereferencestring/FRS.
Thanks for pippenger- please rebase on main though; there may be some new
types… also… FRS might touch that. I’ll look at my local FRS work tonight-
if theres a conflict I’ll let you go ahead

**Comment by laudiacay** [comment]
Also- Thank you Colin, you are a king, this is kingly behavior

**Comment by 0xJepsen** [comment]
Love this guys we are approaching escape velocity.

**Comment by lonerapier** [comment]
@laudiacay no we haven't. I don't think it's used anywhere in the MSM algo.

**Comment by Autoparallel** [comment]
Closing this now as completed!
