### ISSUE TITLE
Implement functions in `transcript.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#30]
# Transcript

Here is a list of functions as tasks to complete here:

- [ ] `PedersenBlake3s::hash()`
- [ ] `PlookupPedersenBlake3s::hash()`
- [x] `Transcript::from_serialized()`
- [x] `Transcript::apply_fiat_shamir()`
- [ ] `Transcript::export_transcript()`

--- 

Then we should add in the accompanying tests from [here](https://gist.github.com/shuklaayush/d3952ae12124082b28aa71834e3cafe1).

**Comment by laudiacay** [comment]
this will be covered by #80
