### ISSUE TITLE
TODOs in `polynomials/evaluation_domain.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#31]
# Evaluation Domain

Here are TODOs and implementations as tasks:
- [ ] Implement `EvaluationDomain::compute_generator_table()`

--- 

Then we should add in the accompanying tests from [here](https://gist.github.com/shuklaayush/d3952ae12124082b28aa71834e3cafe1).

**Comment by 0xJepsen** [comment]
Not sure that the compute_generator_table in is used in the c++ version. It has no accompanying logic just a namespace. Can see it here:
https://github.com/AztecProtocol/barretenberg/blob/16720058320e8eacaa660c9a8037db6fc4084b22/cpp/src/barretenberg/polynomials/evaluation_domain.hpp#L37

**Comment by Autoparallel** [comment]
@0xJepsen you are also assigned here
