### ISSUE TITLE
Unimplemented in `srs/reference_string/mem_reference_string.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#34]
# Mem Reference String

There is a single `unimplemented!()` here:

- [ ] VerifierMemReferenceString::new()`

--- 

Then we should add in the accompanying tests from [here](https://gist.github.com/shuklaayush/d3952ae12124082b28aa71834e3cafe1).

**Comment by colinnielsen** [comment]
Test

**Comment by colinnielsen** [comment]
I'll take this one

**Comment by Autoparallel** [comment]
@colinnielsen how's this cookin'?

Do you have any notes for what we need to get done first? Miller lines/algorithm?

**Comment by colinnielsen** [comment]
> @colinnielsen how's this cookin'?
> 
> Do you have any notes for what we need to get done first? Miller lines/algorithm?

Waiting on Claudia's refactor and merge of #60 to move forward with this implementation

**Comment by laudiacay** [comment]
@colinnielsen check it out, it's readyish to merge. see `Filereferencestring` as the example

**Comment by Autoparallel** [comment]
@colinnielsen does this mean you can get back to this?
