### ISSUE TITLE
TODOs in `srs/reference_string/mod.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#35]
# Reference String

Here's the two tasks:

- [ ] Implement `ReferenceStringFactory::get_prover_crs()`
- [ ] Implement `ReferenceStringFactory::get_verifier_crs()`

---

Then we should add in the accompanying tests from [here](https://gist.github.com/shuklaayush/d3952ae12124082b28aa71834e3cafe1).

**Comment by Autoparallel** [comment]
@shuklaayush do you want to start here?

**Comment by shuklaayush** [comment]
Yep, looking into this

**Comment by Autoparallel** [comment]
Assigned

**Comment by laudiacay** [comment]
this doesn't need fixing, i got it in #60 (one liner)
