### ISSUE TITLE
Unimplemented in `srs/reference_string/file_reference_string.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#36]
# File Reference String

One unimplemented function here:

- [ ] Implement VerifierFileReferenceString::new()`

--- 

Then we should add in the accompanying tests from [here](https://gist.github.com/shuklaayush/d3952ae12124082b28aa71834e3cafe1).

**Comment by laudiacay** [comment]
there are more todos in here, partially handled by #60... #60 does not close this yet.
