### ISSUE TITLE
TODOs in `ecc/bn254_scalar_multiplication.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#46]
# BN254 Scalar Multiplication

The following tasks need to get done:
- [ ] Implement `PippengerRuntimeState::new()`
- [ ] Implement `PippengerRuntimeState::pippenger_unsafe()`
- [ ] Implement `PippengerRuntimeState::pippenger()`

**Comment by lonerapier** [comment]
will be done with #28

**Comment by laudiacay** [comment]
closing as duplicate
