### ISSUE TITLE
Unimplemented in `ecc/curves/mod.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#47]
# ECC

We need to:

- [ ] Implement `coset_generator()`
- [ ] Implement `external_coset_generator()`

**Comment by 0xJepsen** [comment]
Can we just use arkworks for this?

**Comment by laudiacay** [comment]
probably not- but- tied/semi-duplicated with #45, doesn't need a fix until this is actively breaking tests.

**Comment by laudiacay** [comment]
duplicate with #45
