### ISSUE TITLE
TODOs in `plonk/proof_system/widgets/transition_widgets/arithmetic_widget.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#49]
# Arithmetic Widget

Implement:
- [ ] `quotient_required_challenges()`
- [ ] `update_required_challenges()`
- [ ] `sum_linear_terms()`
- [ ] `compute_non_linear_terms()`

**Comment by laudiacay** [comment]
note compute_non_linear_terms will never be used and should stay unimplemented
